name: Run Regional
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
        image: para2x/uiuc_custom_full_psims:3.0
        credentials:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        volumes:
            - ${{ github.workspace }}:/pysims/data
    steps:
      - uses: actions/checkout@v2
        with:
            ref: ${{ github.head_ref }}
      - name: test-info
        run: git log --pretty=oneline
      - name: 1-Install git
        run:  apt-get install -y git
        
      - name: 2-Checkout the latest data inputs 
        uses: actions/checkout@main
        with:
          repository: FarmerAssist/ModelInputs
          path: Data
          
      - name: 3-Checkout the latest simulation
        uses: actions/checkout@v2
        with:
          repository: FarmerAssist/Simulation
          path: Sims
          
      - name: 4-Checkout the latest pSIMS
        uses: actions/checkout@v2
        with:
          repository: AgronomicForecastingLab/pysims
          token: ${{ secrets.GITHUBTOKEN }}
          path: pysims
     
      - name: 5-Run the model
        run: |
          . /pysims/data/Sims/Champaign/test_apsim_TL.sh   
            
      - name: 6- Commit the model outputs
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "[Bot] Update all the things!"
          repository: /pysims/data/
      

      

