name: Run Regional
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
        image: para2x/uiuc_custom_full_psims:latest
        credentials:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        volumes:
            - ${{ github.workspace }}:/pysims/data
    steps:
 #     - run: echo "${{ github.event_name }}, ${{ runner.os }}, ${{ github.ref }}, ${{ github.repository }}, ${{ github.repository }}, ${{ job.status }}"
      
      - name: 1- Checkout the latest data inputs 
        uses: actions/checkout@main
        with:
          repository: FarmerAssist/ModelInputs
          path: Data
          
      - name: 2- Checkout the latest simulation
        uses: actions/checkout@v2
        with:
          repository: FarmerAssist/Simulation
          path: Sims
          
      - name: 3- Checkout the latest pSIMS
        uses: actions/checkout@v2
        with:
          repository: AgronomicForecastingLab/pysims
          token: ${{ secrets.GITHUBTOKEN }}
          path: pysims
     
      - name: 4- Run the model
        run: |
          . /pysims/data/Sims/Champaign/test_apsim_TL.sh   
          
      - name: 5- Cleaning the outputs
        run: |
          rm /pysims/data/*.nc /pysims/data/*.tar /pysims/data/*.nc4             
      - name: List files in the repository
        run: |
          ls -R /pysims/data

