name: Run Regional
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
        image: para2x/uiuc_custom_full_psims:latest
        volumes:
            - ${{ github.workspace }}:/mydatadir
    steps:
      - uses: actions/checkout@v1
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin
      - run: echo "${{ github.event_name }}, ${{ runner.os }}, ${{ github.ref }}, ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "${{ github.repository }}, ${{ job.status }}"
      - name: List files in the repository
        run: |
          ls /mydatadir
