name: Run Regional
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    container:
        image: para2x/uiuc_custom_full_psims:latest
        credentials:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_PASSWORD }}
        volumes:
            - ${{ github.workspace }}:/pysims/data
    steps:
      - run: echo "${{ github.event_name }}, ${{ runner.os }}, ${{ github.ref }}, ${{ github.repository }}"
      - name: Check out repository code
        uses: actions/checkout@v2
      - run: echo "${{ github.repository }}, ${{ job.status }}"
      - name: Check out the latest pSIMS
        uses: actions/checkout@main
        with:
          repository: AgronomicForecastingLab/pysims
          token: ${{ secrets.GITHUBTOKEN }}
      - run : mkdir pysims
      - run : mv -v /pysims/data/* /pysims/data/pysims
      - name: Check out the latest data inputs
        uses: actions/checkout@main
        with:
          repository: FarmerAssist/ModelInputs
      - name: Check out the latest simulation
        uses: actions/checkout@main
        with:
          repository: FarmerAssist/Simulation
      - name: List files in the repository
        run: |
          ls -R /pysims/data
